apiVersion: template.openshift.io/v1
kind: Template
objects:

  - kind: Deployment
    apiVersion: apps/v1
    metadata:
      name: ${APP_NAME}
      namespace: ${APP_NAMESPACE}
      labels:
        app: ${APP_NAME}
        app.kubernetes.io/name: ${APP_NAME}
        app.openshift.io/runtime: python
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: ${APP_NAME}
      template:
        metadata:
          labels:
            app: ${APP_NAME}
            deployment: ${APP_NAME}
        spec:
          containers:
            - name: ${APP_NAME}
              image: quay.io/alopezme/python-observability-app:latest
              imagePullPolicy: Always
              ports:
                - containerPort: 8080
                  protocol: TCP
              env:
                - name: GREETINGS_NAME
                  value: Alvaro
              livenessProbe:
                httpGet:
                  path: /health/live
                  port: 8080
                  scheme: HTTP
                timeoutSeconds: 1
                periodSeconds: 10
                successThreshold: 1
                failureThreshold: 3
              readinessProbe:
                httpGet:
                  path: /health/ready
                  port: 8080
                  scheme: HTTP
                timeoutSeconds: 1
                periodSeconds: 10
                successThreshold: 1
                failureThreshold: 3
              resources:
                limits:
                  cpu: 1
                  memory: 500Mi
                requests:
                  cpu: 100m
                  memory: 50Mi
              securityContext:
                allowPrivilegeEscalation: false
                capabilities:
                  drop:
                  - ALL
          securityContext:
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
          terminationGracePeriodSeconds: 5

  - kind: Service
    apiVersion: v1
    metadata:
      name: ${APP_NAME}
      namespace: ${APP_NAMESPACE}
      labels:
        app: ${APP_NAME}
    spec:
      ports:
        - name: 8080-tcp
          protocol: TCP
          port: 8080
          targetPort: 8080
      type: ClusterIP
      selector:
        app: ${APP_NAME}
        deployment: ${APP_NAME}

  - kind: Route
    apiVersion: route.openshift.io/v1
    metadata:
      name: ${APP_NAME}
      namespace: ${APP_NAMESPACE}
      labels:
        app: ${APP_NAME}
    spec:
      to:
        kind: Service
        name: ${APP_NAME}
      port:
        targetPort: 8080-tcp
      tls:
        termination: edge
        insecureEdgeTerminationPolicy: Redirect
      wildcardPolicy: None

parameters:
  - name: APP_NAMESPACE
    description: "The project where the application will be deployed."
    required: false
    value: quarkus-observability
  - name: APP_NAME
    description: "The name of the application."
    required: false
    value: python
